### ISSUE TITLE
Possible memory leak when loading multiple SOFA files

### ISSUE THREAD

**Issue by peterdodds-fb** [OneBadNinja/SOFASonix#2]
In the SOFASonix/SOFASonix.py `load()` method, the NetCDF4 file that is used to create the SOFASonix object is closed, but the raw file is never dereferenced. It appears that because of the persistent reference, the memory held by the raw object increases when sequentially loading multiple larger SOFA files even if the reference to the SOFASonix object is removed.

I was able to resolve the issue on my local branch by adding `del raw` following the `raw.close()` on line 436 so that the object is dereferenced before garbage collection. If this solution is acceptable, I can PR my local branch.

**Comment by OneBadNinja** [comment]
Hi Peter! Apologies for the late reply, I've not been very active here recently! Thank you for resolving this! Quite a harmless addition too, feel free to PR your branch!

**Comment by peterdodds-fb** [comment]
Just PR'd. Thanks!

**Comment by OneBadNinja** [comment]
Thanks Peter! All done!
